//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string COLLISION1_3 = "collision1_3";
        
        public const string COLLISION1_2 = "collision1_2";
        
        public const string GAME_START = "game_start";
        
        public const string COLLISION1_1 = "collision1_1";
    }
}
